# Cross Fold Validation

In [2]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

digits = load_digits()

In [3]:
# Splitting data (each time of execution train test split changes data set sequence)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [4]:
# Logistic regression used for classifying categorical dependent variable from set of independent variable
lr =LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\ashoaib\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [5]:
# SVM classifier
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9907407407407407

In [6]:
# RandomForest Clasifier
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test, y_test)

0.9851851851851852

In [7]:
# Solution of problem from train_test_split Kfold comes into exist
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
# Accessing Kfold Way
for train_index, test_index in kf.split(range(20)):
    print(train_index, test_index)

[ 7  8  9 10 11 12 13 14 15 16 17 18 19] [0 1 2 3 4 5 6]
[ 0  1  2  3  4  5  6 14 15 16 17 18 19] [ 7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13] [14 15 16 17 18 19]


In [8]:
# Method for repeated calling a model
def  get_score(model, X_train,X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test,y_test)

In [9]:
# Straitified KFold
from sklearn.model_selection import StratifiedKFold
folds =  StratifiedKFold(n_splits=3)

score_lr = []
score_svm = []
score_rf = []

In [10]:
for train_index, test_index in kf.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    score_lr.append(get_score( LogisticRegression(),X_train, X_test, y_train, y_test))
    score_svm.append(get_score( SVC(),X_train, X_test, y_train, y_test))
    score_rf.append(get_score( RandomForestClassifier(n_estimators=40),X_train, X_test, y_train, y_test))

C:\Users\ashoaib\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ashoaib\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_i

In [11]:
# Replacing all above code into one file
from sklearn.model_selection import cross_val_score
print(cross_val_score(LogisticRegression(max_iter=10), digits.data, digits.target))
print(score_lr)

[0.93611111 0.86944444 0.93314763 0.94150418 0.88579387]
[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]


C:\Users\ashoaib\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ashoaib\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_i